### ISSUE TITLE
Building without an src directory

### ISSUE THREAD

**Issue by tspivey** [demonnic/muddler#25]
If you build without an src directory, muddler creates build and fails with a java exception:
```
MUDDLER: [INFO]: Beginning build. Using muddler version 0.10
MUDDLER: [INFO]: Package name not set via mfile, using directory name
MUDDLER: [INFO]: Name       : test
MUDDLER: [INFO]: Spinning up new AntBuilder to do our dirty work but making it silent
MUDDLER: [INFO]: Cleaning build directory
MUDDLER: [INFO]: Filtering @PKGNAME@ to 'test' and @VERSION@ to ''
Exception in thread "main" : C:\Users\tyler\test\src does not exist.
        at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:512)
        at org.apache.tools.ant.taskdefs.Copy.execute(Copy.java:494)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at groovy.util.AntBuilder.performTask(AntBuilder.java:335)
        at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:280)
        at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:160)
        at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:215)
        at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:74)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at muddler.App.main(App.groovy:104)```

I think it should check for src before doing anything else, otherwise I have an unwanted build directory around if I run it from inside my project.

**Comment by demonnic** [comment]
This should be fixed in 0.12
