### ISSUE TITLE
Catch exceptions and give better error messages (Mainly, file names)

### ISSUE THREAD

**Issue by stridera** [demonnic/muddler#6]
Got an error, but I wasn't sure where.  Had to check all my json files to find the error.

```     [copy] Copying 22 files to /home/strider/Code/FierymudMudletClient/build/filtered/src
Exception in thread "main" groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is ']' with an int value of 93
Unable to determine the current character, it is not a string, number, array, or object
line number 11
index number 165
]
^
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:202)
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonArray(JsonParserCharArray.java:322)
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:178)```

**Comment by stridera** [comment]
Another example:
```     [copy] Copying 22 files to /home/strider/Code/FierymudMudletClient/build/filtered/src
Exception in thread "main" groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is ']' with an int value of 93
Unable to determine the current character, it is not a string, number, array, or object
line number 11
index number 165
]
^
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:202)
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonArray(JsonParserCharArray.java:322)
        at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:178)```

**Comment by demonnic** [comment]
Yeah, I played a bit fast and loose with the code, should add more try/catch all around honestly.

**Comment by Kebap** [comment]
This has been improved with release 0.7 - give it a test and report back, if you need additional improvements 😉

**Comment by demonnic** [comment]
Also, sorry it took so long.

**Comment by demonnic** [comment]
mis-clicked.
